name: Autograding Tests
'on': {}
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: bubble1
      id: bubble1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: bubble1
        setup-command: make
        command: "./sort bubble  6 5 2 3"
        input: ''
        expected-output: |2-
              6    5    2    3
              6    5    2    3
              6    5    2    3
              6    5    3    2
        comparison-method: contains
        timeout: 10
        max-score: 11
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUBBLE_RESULTS: "${{steps.bubble.outputs.result}}"
      with:
        runners: bubble
  - name: bubble2
      id: bubble2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: bubble1
        setup-command: make
        command: "./sort bubble  1 5 2 3"
        input: ''
        expected-output: |2-
              5    1    2    3
              5    2    1    3
              5    2    3    1  
        comparison-method: contains
        timeout: 10
        max-score: 12
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUBBLE_RESULTS: "${{steps.bubble.outputs.result}}"
      with:
        runners: bubble